---
- name: Setup shell
  block:
    - name: Create tmp nushell dir
      ansible.builtin.file:
        path: "{{ nushell_tar_directory }}"
        state: directory
        mode: "0600"

    - name: Download nushell archive
      ansible.builtin.get_url:
        url: "https://github.com/nushell/nushell/releases/download/{{ nushell_version }}/nu-{{ nushell_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ nushell_tar_file }}"
        mode: "0600"

    - name: Unarchive nushell tar
      ansible.builtin.unarchive:
        src: "{{ nushell_tar_file }}"
        dest: "{{ nushell_tar_directory }}"
        remote_src: true

    - name: Copy nushell binary to destination directory
      ansible.builtin.copy:
        src: "{{ nushell_tar_directory }}/nu-{{ nushell_version }}-x86_64-unknown-linux-gnu/{{ item }}"
        dest: "{{ nushell_bin_directory }}/{{ item }}"
        mode: "{{ nushell_binary_mode }}"
        owner: "{{ ansible_user }}"
        remote_src: true
      with_items: "{{ nushell_wanted_plugins + ['nu'] }}"

    # - name: Set nushell as default shell
    #   ansible.builtin.user:
    #     name: ansible_user
    #     shell: /usr/local/bin/nu
