---
- name: Create tmp nushell dir
  ansible.builtin.file:
    path: "{{ nushell.tar_directory }}"
    state: directory
    mode: "0600"

- name: Download nushell archive
  ansible.builtin.get_url:
    url: "https://github.com/nushell/nushell/releases/download/{{ nushell.version }}/nu-{{ nushell.version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ nushell.tar_file }}"
    mode: "0600"

- name: Unarchive nushell tar
  ansible.builtin.unarchive:
    src: "{{ nushell.tar_file }}"
    dest: "{{ nushell.tar_directory }}"
    remote_src: true

- name: Copy nushell binary to destination directory
  ansible.builtin.copy:
    src: "{{ nushell.tar_directory }}/nu-{{ nushell.version }}-x86_64-unknown-linux-gnu/{{ item }}"
    dest: "{{ nushell.bin_directory }}/{{ item }}"
    mode: "{{ nushell.binary_mode }}"
    owner: "{{ ansible_user }}"
    remote_src: true
  with_items: "{{ nushell.wanted_plugins + ['nu'] }}"

- name: Add nushell to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /usr/local/bin/nu
    state: present
  become: true
