all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: 192.168.1.10
          ansible_user: root

    k8s:
      hosts:
        k8s-node-01:
          ansible_host: 10.13.13.1
          ansible_user: ubuntu

    # gateway: nodes that serve as the public VPN entry point.
    # Runs WireGuard host prereqs and DuckDNS.
    # In a multi-node cluster only list the node(s) that are exposed.
    gateway:
      hosts:
        k8s-node-01:
          ansible_host: 10.13.13.1
          ansible_user: ubuntu

    # A single node must be choosen to host the media stack
    media:
      hosts:
        k8s-node-01:
          ansible_host: 10.13.13.1
          ansible_user: ubuntu
