- name: Create torrents download directory
  ansible.builtin.file:
    path: /mnt/downloads/torrents
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"

- name: Create music library directory
  ansible.builtin.file:
    path: /mnt/media/music
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"

- name: Create youtube-dl staging directory
  ansible.builtin.file:
    path: /mnt/downloads/youtube
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
