---
- name: Execute Media Stack deployments locally
  delegate_to: localhost
  become: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ local_kubeconfig }}"
  block:
    # ── Common Kube Resources ──────────────────────────────────────────────────────
    - name: Infrastructure - Common Dependencies
      tags: [media_infra, media_common]
      block:
        - name: Namespace
          kubernetes.core.k8s:
            template: namespace.yml
            state: present
        - name: Media stack shared storage
          kubernetes.core.k8s:
            template: storage.yml.j2
            state: present
          tags: [media_infra, storage]

    # ── QBittorrent ───────────────────────────────────────────────────────────────
    - name: App - QBittorrent
      tags: [qbittorrent]
      block:
        - name: QBittorrent storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: qbittorrent/storage.yml
            state: present
        - name: QBittorrent config
          kubernetes.core.k8s:
            template: qbittorrent/config.yml
            state: present
        - name: QBittorrent service
          kubernetes.core.k8s:
            template: qbittorrent/service.yml
            state: present
        - name: QBittorrent deployment
          kubernetes.core.k8s:
            template: qbittorrent/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Prowlarr ───────────────────────────────────────────────────────────────

    - name: App - Prowlarr
      tags: [prowlarr]
      block:
        - name: Prowlarr storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: prowlarr/storage.yml
            state: present
        - name: Prowlarr config
          kubernetes.core.k8s:
            template: prowlarr/config.yml.j2
            state: present
        - name: Prowlarr service
          kubernetes.core.k8s:
            template: prowlarr/service.yml
            state: present
        - name: Prowlarr ingress
          kubernetes.core.k8s:
            template: prowlarr/ingress.yml
            state: present
        - name: Prowlarr deployment
          kubernetes.core.k8s:
            template: prowlarr/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Lidarr ───────────────────────────────────────────────────────────────

    - name: App - Lidarr
      tags: [lidarr]
      block:
        - name: Lidarr storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: lidarr/storage.yml
            state: present
        - name: Lidarr config
          kubernetes.core.k8s:
            template: lidarr/config.yml.j2
            state: present
        - name: Lidarr service
          kubernetes.core.k8s:
            template: lidarr/service.yml
            state: present
        - name: Lidarr ingress
          kubernetes.core.k8s:
            template: lidarr/ingress.yml
            state: present
        - name: Lidarr deployment
          kubernetes.core.k8s:
            template: lidarr/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Nextcloud ────────────────────────────────────────────────────────────

    - name: App - Nextcloud
      tags: [nextcloud]
      block:
        - name: Nextcloud DB storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: nextcloud/db-storage.yml.j2
            state: present
        - name: Nextcloud DB service
          kubernetes.core.k8s:
            template: nextcloud/db-service.yml
            state: present
        - name: Nextcloud DB deployment
          kubernetes.core.k8s:
            template: nextcloud/db-deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120
        - name: Nextcloud storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: nextcloud/storage.yml.j2
            state: present
        - name: Nextcloud service
          kubernetes.core.k8s:
            template: nextcloud/service.yml
            state: present
        - name: Nextcloud ingress
          kubernetes.core.k8s:
            template: nextcloud/ingress.yml
            state: present
        - name: Nextcloud deployment
          kubernetes.core.k8s:
            template: nextcloud/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 300

    # ── Beets ───────────────────────────────────────────────────────────────

    - name: App - Beets
      tags: [beets]
      block:
        - name: Beets tag config
          kubernetes.core.k8s:
            template: beets/config.yml.j2
            state: present
        - name: Beets tag cronjob
          kubernetes.core.k8s:
            template: beets/cronjob.yml.j2
            state: present

    # ── youtube-dl ──────────────────────────────────────────────────────────

    - name: App - youtube-dl utility pod
      tags: [youtube-dl]
      block:
        - name: beets download config
          kubernetes.core.k8s:
            template: youtube-dl/beets-download-config.yml.j2
            state: present
        - name: download script config
          kubernetes.core.k8s:
            template: youtube-dl/download-script.yml.j2
            state: present
        - name: youtube-dl deployment
          kubernetes.core.k8s:
            template: youtube-dl/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 180

    # ── jellyfin ────────────────────────────────────────────────────────────────

    - name: App - Jellyfin
      tags: [jellyfin]
      block:
        - name: Jellyfin storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: jellyfin/storage.yml
            state: present
        - name: Jellyfin network config
          kubernetes.core.k8s:
            template: jellyfin/config.yml
            state: present
        - name: Jellyfin service
          kubernetes.core.k8s:
            template: jellyfin/service.yml
            state: present
        - name: Jellyfin ingress
          kubernetes.core.k8s:
            template: jellyfin/ingress.yml
            state: present
        - name: Jellyfin deployment
          kubernetes.core.k8s:
            template: jellyfin/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120
