---
- name: Execute Media Stack deployments locally
  delegate_to: localhost
  become: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ local_kubeconfig }}"
  block:
    # ── Common Kube Resources ──────────────────────────────────────────────────────
    - name: Infrastructure - Common Dependencies
      tags: [media_infra, media_common]
      block:
        - name: Namespace
          kubernetes.core.k8s:
            template: namespace.yml
            state: present
        - name: Media stack shared storage
          kubernetes.core.k8s:
            template: storage.yml.j2
            state: present
          tags: [media_infra, storage]

    # ── QBittorrent ───────────────────────────────────────────────────────────────
    - name: App - QBittorrent
      tags: [qbittorrent]
      block:
        - name: QBittorrent storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: qbittorrent/storage.yml
            state: present
        - name: QBittorrent config
          kubernetes.core.k8s:
            template: qbittorrent/config.yml
            state: present
        - name: QBittorrent service
          kubernetes.core.k8s:
            template: qbittorrent/service.yml
            state: present
        - name: QBittorrent deployment
          kubernetes.core.k8s:
            template: qbittorrent/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Prowlarr ───────────────────────────────────────────────────────────────

    - name: App - Prowlarr
      tags: [prowlarr]
      block:
        - name: Prowlarr storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: prowlarr/storage.yml
            state: present
        - name: Prowlarr config
          kubernetes.core.k8s:
            template: prowlarr/config.yml.j2
            state: present
        - name: Prowlarr service
          kubernetes.core.k8s:
            template: prowlarr/service.yml
            state: present
        - name: Prowlarr ingress
          kubernetes.core.k8s:
            template: prowlarr/ingress.yml
            state: present
        - name: Prowlarr deployment
          kubernetes.core.k8s:
            template: prowlarr/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Lidarr ───────────────────────────────────────────────────────────────

    - name: App - Lidarr
      tags: [lidarr]
      block:
        - name: Lidarr storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: lidarr/storage.yml
            state: present
        - name: Lidarr config
          kubernetes.core.k8s:
            template: lidarr/config.yml.j2
            state: present
        - name: Lidarr service
          kubernetes.core.k8s:
            template: lidarr/service.yml
            state: present
        - name: Lidarr ingress
          kubernetes.core.k8s:
            template: lidarr/ingress.yml
            state: present
        - name: Lidarr deployment
          kubernetes.core.k8s:
            template: lidarr/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Nextcloud ────────────────────────────────────────────────────────────

    - name: App - Nextcloud
      tags: [nextcloud]
      block:
        - name: Nextcloud DB storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: nextcloud/db-storage.yml.j2
            state: present
        - name: Nextcloud DB service
          kubernetes.core.k8s:
            template: nextcloud/db-service.yml
            state: present
        - name: Nextcloud DB deployment
          kubernetes.core.k8s:
            template: nextcloud/db-deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120
        - name: Nextcloud storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: nextcloud/storage.yml.j2
            state: present
        - name: Nextcloud service
          kubernetes.core.k8s:
            template: nextcloud/service.yml
            state: present
        - name: Nextcloud ingress
          kubernetes.core.k8s:
            template: nextcloud/ingress.yml
            state: present
        - name: Nextcloud deployment
          kubernetes.core.k8s:
            template: nextcloud/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 300

    # ── Beets ───────────────────────────────────────────────────────────────

    - name: App - Beets
      tags: [beets]
      block:
        - name: Beets config
          kubernetes.core.k8s:
            template: beets/config.yml.j2
            state: present
        - name: Beets cronjob
          kubernetes.core.k8s:
            template: beets/cronjob.yml.j2
            state: present

    # ── jellyfin ────────────────────────────────────────────────────────────────

    - name: App - Jellyfin
      tags: [jellyfin]
      block:
        - name: Jellyfin storage (PVs and PVCs)
          kubernetes.core.k8s:
            template: jellyfin/storage.yml
            state: present
        - name: Jellyfin network config
          kubernetes.core.k8s:
            template: jellyfin/config.yml
            state: present
        - name: Jellyfin service
          kubernetes.core.k8s:
            template: jellyfin/service.yml
            state: present
        - name: Jellyfin ingress
          kubernetes.core.k8s:
            template: jellyfin/ingress.yml
            state: present
        - name: Jellyfin deployment
          kubernetes.core.k8s:
            template: jellyfin/deployment.yml.j2
            state: present
            wait: true
            wait_condition:
              type: Available
              status: "True"
            wait_timeout: 120

    # ── Prowlarr ↔ Lidarr application link ───────────────────────────────────

    - name: Sync Prowlarr - Lidarr application link
      tags: [lidarr]
      block:
        - name: Get Prowlarr applications
          uri:
            url: "http://{{ ansible_host }}:{{ k8s_ingress_http_nodeport }}/media/prowlarr/api/v1/applications"
            headers:
              X-Api-Key: "{{ lookup('env', 'ARR_API_KEY') | mandatory }}"
          register: prowlarr_apps

        - name: Set Lidarr app fact
          set_fact:
            _lidarr_app: "{{ prowlarr_apps.json | selectattr('name', 'equalto', 'Lidarr') | list | first | default({}) }}"

        - name: Create And Configure Lidarr in Prowlarr
          when: _lidarr_app.id is not defined
          uri:
            url: "http://{{ ansible_host }}:{{ k8s_ingress_http_nodeport }}/media/prowlarr/api/v1/applications"
            method: POST
            headers:
              X-Api-Key: "{{ lookup('env', 'ARR_API_KEY') | mandatory }}"
            body_format: json
            body:
              name: Lidarr
              syncLevel: addOnly
              implementationName: Lidarr
              implementation: Lidarr
              configContract: LidarrSettings
              tags: []
              fields:
                - { name: prowlarrUrl, value: "http://prowlarr:9696" }
                - { name: baseUrl, value: "http://lidarr:8686/media/lidarr" }
                - {
                    name: apiKey,
                    value: "{{ lookup('env', 'ARR_API_KEY') | mandatory }}",
                  }
                - {
                    name: syncCategories,
                    value: [3000, 3010, 3030, 3040, 3050, 3060],
                  }
                - {
                    name: syncRejectBlocklistedTorrentHashesWhileGrabbing,
                    value: false,
                  }
            status_code: 201
