- name: Set Media manifest directory
  ansible.builtin.set_fact:
    media_template_dir: "{{ playbook_dir }}/../roles/media/templates"

# ── Common Kube Resources ──────────────────────────────────────────────────────

- name: Namespace
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/namespace.yml"
    state: present

- name: Media stack storage (PVs and PVCs)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', media_template_dir + '/storage.yml') | from_yaml_all | list }}"
    state: present

# ── QBittorrent ───────────────────────────────────────────────────────────────

- name: QBittorrent storage (PVs and PVCs)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', media_template_dir + '/qbittorrent/storage.yml') | from_yaml_all | list }}"
    state: present

- name: QBittorrent config
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/qbittorrent/config.yml"
    state: present

- name: QBittorrent deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', media_template_dir + '/qbittorrent/deployment.yml.j2') | from_yaml }}"
    state: present
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120

- name: QBittorrent service
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/qbittorrent/service.yml"
    state: present

# ── Prowlarr ───────────────────────────────────────────────────────────────

- name: Prowlarr storage (PVs and PVCs)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', media_template_dir + '/prowlarr/storage.yml') | from_yaml_all | list }}"
    state: present

- name: Prowlarr config
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/prowlarr/config.yml.j2"
    state: present

- name: Prowlarr deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', media_template_dir + '/prowlarr/deployment.yml.j2') | from_yaml }}"
    state: present
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120

- name: Prowlarr service
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/prowlarr/service.yml"
    state: present

# ── Lidarr ───────────────────────────────────────────────────────────────

- name: Lidarr storage (PVs and PVCs)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', media_template_dir + '/lidarr/storage.yml') | from_yaml_all | list }}"
    state: present

- name: Lidarr config
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/lidarr/config.yml.j2"
    state: present

- name: Lidarr deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', media_template_dir + '/lidarr/deployment.yml.j2') | from_yaml }}"
    state: present
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120

- name: Lidarr service
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/lidarr/service.yml"
    state: present

# ── jellyfin ────────────────────────────────────────────────────────────────

- name: Jellyfin storage (PVs and PVCs)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', media_template_dir + '/jellyfin/storage.yml') | from_yaml_all | list }}"
    state: present

- name: Jellyfin network config
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/jellyfin/config.yml"
    state: present

- name: Jellyfin deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', media_template_dir + '/jellyfin/deployment.yml.j2') | from_yaml }}"
    state: present
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120

- name: Jellyfin service
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/jellyfin/service.yml"
    state: present

- name: Jellyfin ingress
  kubernetes.core.k8s:
    src: "{{ media_template_dir }}/jellyfin/ingress.yml"
    state: present
