---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-config-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/wireguard/config
    type: DirectoryOrCreate
  claimRef:
    namespace: wireguard
    name: wireguard-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config-pvc
  namespace: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: wireguard-config-pv
