---
- name: Harden SSH
  ansible.builtin.import_tasks: harden_ssh_up.yml
  tags: [proxmox_ssh, harden]

- name: Configure NIC for WireGuard UDP traffic
  ansible.builtin.import_tasks: nic_up.yml
  tags: [proxmox_nic]
