defaultNamespace: monitoring
helm:
  releaseName: monitoring
  valuesFiles:
    # - values/prometheus-values.yaml
    - values/grafana.yaml
    # - values/victoriametrics-values.yaml
repositories:
  # - name: prometheus-community
  #   url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
    version: 8.13.1
  # - name: victoria-metrics
  #   url: https://victoriametrics.github.io/helm-charts
charts:
  # - name: prometheus
  #   repo: prometheus-community
  #   namespace: monitoring
  - name: grafana
    repo: grafana
    namespace: monitoring
  # - name: victoria-metrics-single
  #   repo: victoria-metrics
  #   namespace: monitoring
  #
