apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-network-config
  namespace: media
data:
  network.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <BaseUrl>/media/jellyfin</BaseUrl>
      <RequireHttps>false</RequireHttps>
      <EnableHttps>false</EnableHttps>
    </NetworkConfiguration>
