- name: System prerequisites
  ansible.builtin.import_tasks: host_up.yml
  tags: [wireguard_prereqs]

- name: Deploy on k8s
  ansible.builtin.import_tasks: k8s_up.yml
  tags: [wireguard_k8s_install, network]
