---
- name: Infrastructure - Proxmox
  hosts: proxmox
  become: true
  roles:
    - role: proxmox
  tags: [proxmox, infra]

- name: Kubernetes - Host & Cluster Layer
  hosts: k8s
  become: true
  roles:
    - role: common
      tags: [common]
    - role: k8s
      tags: [k8s, cluster]
  tags: [k8s]

- name: Network - Gateway Layer
  hosts: gateway
  become: true
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ local_kubeconfig }}"
  tasks:
    - name: Label Node as Gateway
      delegate_to: localhost
      become: false
      kubernetes.core.k8s:
        kubeconfig: "~/.kube/casshome.conf"
        kind: Node
        name: "{{ inventory_hostname }}"
        definition:
          metadata:
            labels:
              network-role: gateway
      tags: [k8s_labels]

    - name: Import DuckDNS and Wireguard
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - duckdns
        - wireguard
      tags: [gateway, network]

- name: Apps - Media Stack Layer
  hosts: media
  become: true
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ local_kubeconfig }}"
  tasks:
    - name: Label Node as Media
      delegate_to: localhost
      become: false
      kubernetes.core.k8s:
        kubeconfig: "~/.kube/casshome.conf"
        kind: Node
        name: "{{ inventory_hostname }}"
        definition:
          metadata:
            labels:
              stack-role: media
      tags: [k8s_labels]
    - name: Deploy Media Stack
      ansible.builtin.import_role:
        name: media_stack
      tags: [media_stack, apps]
