---
- name: Prepare Host For Wireguard
  hosts: gateway
  become: true
  tasks:
    - name: Run host-level prerequisites
      ansible.builtin.import_role:
        name: wireguard
        tasks_from: host-prerequisites.yml

- name: WireGuard k8s deployment
  hosts: gateway
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      verify_ssl: false
      kubeconfig: "~/.kube/casshome.conf"
  roles:
    - wireguard
