---
- name: Prepare WireGuard Host
  hosts: gateway
  become: true
  tasks:
    - name: Run host-level prep
      ansible.builtin.include_role:
        name: k8s
        tasks_from: wireguard_host.yml

- name: Deploy WireGuard Workload
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "../inventory/group_vars/all.yml"
  roles:
    - role: wireguard
      vars:
        ansible_kubernetes_vars:
          kubeconfig: "~/.kube/casshome.conf"
