# NOTE: Flannel does not enforce NetworkPolicy.
# These policies will take effect if the CNI is switched to Calico or Cilium.
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wireguard-egress
  namespace: wireguard
spec:
  podSelector:
    matchLabels:
      app: wireguard
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: jellyfin
