---
media_stack_busybox_version: "1.37.0"
media_stack_qbittorrent_version: "5.1.0"
media_stack_prowlarr_version: "2.3.0.5236-ls138"
media_stack_lidarr_version: "nightly-3.1.2.4914-ls188"
media_stack_jellyfin_version: "10.11.8"
media_stack_beets_version: "2.8.0-ls322"
