---
k8s_version: "1.32" # minor version — used for apt repo path
k8s_pod_cidr: "10.244.0.0/16"
k8s_service_cidr: "10.96.0.0/12"
k8s_admin_user: "ubuntu"
k8s_flannel_version: "v0.26.2"
k8s_ingress_nginx_chart_version: "4.12.0"
