---
- name: Deploy Calico locally
  delegate_to: localhost
  become: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ local_kubeconfig }}"
  block:
    - name: Add Calico (Tigera) Helm repo
      ansible.builtin.command: helm repo add projectcalico https://docs.tigera.io/calico/charts
      changed_when: false

    - name: Update Helm repos
      ansible.builtin.command: helm repo update
      changed_when: false

    - name: Install Calico via Tigera operator Helm chart
      ansible.builtin.command: >
        helm upgrade --install calico projectcalico/tigera-operator
        --namespace tigera-operator
        --create-namespace
        --version {{ k8s_calico_chart_version }}
        --set "installation.calicoNetwork.ipPools[0].cidr={{ k8s_pod_cidr }}"
        --set "installation.calicoNetwork.ipPools[0].encapsulation=IPIP"
      environment:
        KUBECONFIG: "{{ local_kubeconfig }}"
      changed_when: false

    - name: Wait for Calico node to be ready
      changed_when: false
      register: calico_ready
      retries: 10
      delay: 15
      until: calico_ready.rc == 0
      ansible.builtin.command: >
        kubectl --kubeconfig {{ local_kubeconfig }}
        -n calico-system wait daemonset/calico-node
        --for=jsonpath='{.status.numberReady}'=1 --timeout=300s

    - name: Wait for node to be Ready
      changed_when: false
      register: node_ready
      retries: 5
      delay: 15
      until: node_ready.rc == 0
      ansible.builtin.command: >
        kubectl --kubeconfig {{ local_kubeconfig }}
        wait node --all
        --for=condition=Ready --timeout=300s
