---
- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Deploy containerd configuration
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"
  notify: Restart containerd

- name: Flush handlers to apply containerd config changes
  ansible.builtin.meta: flush_handlers

- name: Enable and start containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: started
