# when moving to multi-cluster setup this must be executed only for one node?
- name: Extract Kubeconfig to local machine
  block:
    - name: Read kubeconfig from node
      ansible.builtin.slurp:
        src: /etc/kubernetes/admin.conf
      register: remote_kubeconfig
      become: true

    - name: Save kubeconfig locally with corrected server IP
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        content: "{{ remote_kubeconfig.content | b64decode | replace('http://127.0.0.1', 'https://{{ ansible_host }}') }}"
        dest: "{{ local_kubeconfig }}"
        mode: "0600"
