# when moving to multi-cluster setup this must be executed only once
- name: Extract Kubeconfig to local machine
  block:
    - name: Read kubeconfig from node
      ansible.builtin.slurp:
        src: /etc/kubernetes/admin.conf
      register: remote_kubeconfig
      become: true

    - name: Save kubeconfig locally with corrected server IP
      ansible.builtin.copy:
        content: >
          {{ remote_kubeconfig.content | b64decode
             | replace('https://127.0.0.1:6443', 'https://' + wireguard_ip + ':6443')
             | replace('https://localhost:6443', 'https://' + wireguard_ip + ':6443') }}
        dest: "{{ local_kubeconfig }}" # ── Unified path
        mode: "0600"
