---
- name: System prerequisites
  ansible.builtin.import_tasks: prereqs.yml
  tags: prereqs

- name: Set up containerd runtime
  ansible.builtin.import_tasks: containerd.yml
  tags: containerd

- name: Install Kubernetes packages
  ansible.builtin.import_tasks: k8s_packages.yml
  tags: k8s_packages

- name: Initialize Kubernetes cluster
  ansible.builtin.import_tasks: kubeadm_init.yml
  tags: kubeadm

- name: Install Helm
  ansible.builtin.import_tasks: helm.yml
  tags: helm

- name: Install Calico CNI
  ansible.builtin.import_tasks: cni.yml
  tags: cni

- name: Install NGINX Ingress Controller
  ansible.builtin.import_tasks: ingress.yml
  tags: ingress

- name: Configure kubectl (alias + autocompletion)
  ansible.builtin.import_tasks: kubectl_config.yml
  tags: kubectl_config

- name: Copy Kubeconfig
  ansible.builtin.import_tasks: copy_kubeconfig.yml
  tags: copy_kubeconfig
