---
- name: System prerequisites
  ansible.builtin.import_tasks: prereqs_up.yml
  tags: [k8s_prereqs]

- name: Set up containerd runtime
  ansible.builtin.import_tasks: containerd_up.yml
  tags: [containerd]

- name: Install Kubernetes packages
  ansible.builtin.import_tasks: k8s_packages_up.yml
  tags: [k8s_pkgs]

- name: Initialize Kubernetes cluster
  ansible.builtin.import_tasks: kubeadm_init_up.yml
  tags: [kubeadm]

# ── All tasks after this one will use the local kubeconfig
- name: Copy Kubeconfig
  ansible.builtin.import_tasks: copy_kubeconfig_up.yml
  tags: [fetch_kubeconfig]

- name: Allow workloads on the single control-plane node
  delegate_to: localhost
  become: false
  kubernetes.core.k8s_taint:
    state: absent
    kubeconfig: "{{ local_kubeconfig }}"
    name: "{{ inventory_hostname }}"
    taints:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
  tags: [kubeadm]

- name: Install Helm
  ansible.builtin.import_tasks: helm_up.yml
  tags: [helm]

- name: Install Calico CNI
  ansible.builtin.import_tasks: cni_up.yml
  tags: [cni]

- name: Install NGINX Ingress Controller
  ansible.builtin.import_tasks: ingress_up.yml
  tags: [ingress]

- name: Configure kubectl (alias + autocompletion)
  ansible.builtin.import_tasks: kubectl_config_up.yml
  tags: [kubectl_config]
