---
- name: System prerequisites
  ansible.builtin.include_tasks: prereqs.yml
  tags: prereqs

- name: Set up containerd runtime
  ansible.builtin.include_tasks: containerd.yml
  tags: containerd

- name: Install Kubernetes packages
  ansible.builtin.include_tasks: k8s_packages.yml
  tags: k8s_packages

- name: Initialize Kubernetes cluster
  ansible.builtin.include_tasks: kubeadm_init.yml
  tags: kubeadm

- name: Install Helm
  ansible.builtin.include_tasks: helm.yml
  tags: helm

- name: Install Calico CNI
  ansible.builtin.include_tasks: cni.yml
  tags: cni

- name: Install NGINX Ingress Controller
  ansible.builtin.include_tasks: ingress.yml
  tags: ingress

- name: Configure kubectl (alias + autocompletion)
  ansible.builtin.include_tasks: kubectl_config.yml
  tags: kubectl_config
